In [1]:
print('hi')

hi


In [4]:
#импортировать библиотеку NumPy
import numpy as np

In [5]:
#Массив из 10 нулей
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#Массив из 10 единиц
b=np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
#Массив из 10 пятерок
c=np.ones(10)*5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
#Массив из целых чисел от 10 до 50
d=np.arange(10,51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [11]:
#Массив из четных чисел от 10 до 50
e=np.arange(10,51,2)
print(e)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [12]:
#Матрица 3х3 с числами от 0 до 8
f=np.arange(0,9).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Единичная матрица 3*3
g=np.ones((3,3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#генерация случайного числа от 0 до 1
h=np.random.rand()
print(h)

0.9070113596134441


In [16]:
#генерация массива из 25 случайных чисел
i=np.random.randn(25)
print(i)

[ 1.24212829 -1.80663221 -0.14475715 -1.06875365 -0.38356895 -0.03634085
 -0.98000572 -0.52270034 -0.02152261 -0.12319471 -0.66072977 -0.14721635
 -0.32514855 -0.40755127 -0.59061578 -0.53945803 -0.69098289 -0.4278909
  1.62482319  0.47092078 -0.56978676  0.99542902 -0.46225907 -1.16877151
 -0.19956021]


In [54]:
#создать матрицу 10*10 от 0,1 до 1,0
j=np.arange(0.01,1.01,0.01).reshape(10,10)
print(j)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [26]:
#запуск стартовой матрицы
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
#Вернуть из стартовой матрицы матрицу (4 столбца последних 3х строк)
k=mat[2:,1:]
print(k)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [39]:
#обращение к элементу со значением 20
l=mat[3,4]
print(l)

20


In [49]:
#обращение к выводу (2,7,12)
m=mat[0:3,1]
n=m.reshape(3,1)
print(n)

[[ 2]
 [ 7]
 [12]]


In [50]:
#вывод последней строки
o=mat[4:,:]
print(o)

[[21 22 23 24 25]]


In [51]:
#вывод последних двух строк
p=mat[3:,:]
print(p)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [52]:
#сумма всех значений в стартовой матрице
print(mat.sum())

325


In [53]:
#сумма значений в колонках в стартовой матрице
print(mat.sum(axis=0))

[55 60 65 70 75]
